# Generated by Django 4.1.5 on 2023-02-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('estado', models.ImageField(default=True, upload_to='')),
            ],
            options={
                'db_table': 'Trabajador',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('estado', models.ImageField(upload_to='')),
                ('id_trabajador', models.CharField(max_length=255)),
                ('_id_trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioApp.trabajador')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
